[package]
name = "fhir-bench-orchestrator"
version = "0.1.0"
authors = ["Karl M. Davis <karl@justdavis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
