version: "3"
services:
  hapi-fhir-jpaserver-start:
    image: "hapiproject/hapi:v5.5.2-distroless"  # Published 2021-11-11.
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - hapi-data:/data/hapi
    volumes:
      - type: bind
        source: ./hapi-data
        target: /data/hapi
        read_only: true
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
    depends_on:
      - "hapi-fhir-mysql"
  hapi-fhir-mysql:
    image: mysql:8.0.27  # Published 2021-10-18.
    container_name: hapi-fhir-mysql
    #https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'